[package]
name = "metrix-utils"
version = "0.1.0"
edition = "2018"
crate-type = "dylib"
authors = ["Jon Fast <jnfstdj656@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }